package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    private Tuple nextTuple;
    private Tuple leftTuple;

    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        child1.open();
        child2.open();

        leftTuple = null;
        nextTuple = findNext();
    }

    public void close() {
        // some code goes here
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();

        leftTuple = null;
        nextTuple = findNext();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        var ans = nextTuple;
        if (ans == null) {
            return null;
        }

        nextTuple = findNext();
        return ans;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return new DbIterator[] {child1, child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        child1 = children[0];
        child2 = children[1];
    }

    @Override
    public Tuple next() throws DbException, TransactionAbortedException, NoSuchElementException {
        var ans = nextTuple;
        if (ans == null) {
            throw new NoSuchElementException();
        }

        nextTuple = findNext();
        return ans;
    }

    @Override
    public boolean hasNext() throws DbException, TransactionAbortedException {
        return nextTuple != null;
    }

    private Tuple findNext() throws DbException, TransactionAbortedException {
        if (leftTuple == null && child1.hasNext()) {
            leftTuple = child1.next();
        }

        while (leftTuple != null) {
            while (child2.hasNext()) {
                var rightTuple = child2.next();
                if (p.filter(leftTuple, rightTuple)) {
                    var next = new Tuple(getTupleDesc());
                    var count = 0;

                    var leftTupleIter = leftTuple.fields();
                    while(leftTupleIter.hasNext()) {
                        var field = leftTupleIter.next();
                        next.setField(count++, field);
                    }

                    var rightTupleIter = rightTuple.fields();
                    while(rightTupleIter.hasNext()) {
                        var field = rightTupleIter.next();
                        next.setField(count++, field);
                    }

                    return next;
                }
            }

            if (child1.hasNext()) {
                leftTuple = child1.next();
                child2.rewind();
            } else {
                leftTuple = null;
            }
        }

        return null;
    }
}
